# Copyright 2021-2026 Louis Héraut <louis.heraut@inrae.fr>*1
#
# *1 INRAE, UR RiverLy, Villeurbanne, France
#
# This file is part of the card Python package.
#
# card is free software: you can redistribute it and/or modify it under
# the terms of the license in the LICENSE file of this repository.

"""Génère docs/CARDS.md, catalogue des fiches CARD, consultable sur GitHub.

Usage (depuis la racine du repo) :
    .python_env/bin/python scripts/generate_catalog.py

À relancer après tout ajout/modification de fiche YAML. Nul besoin d'y
penser : `render()` ne touche à rien, si bien que
`tests/test_catalogue.py` peut confronter les fichiers écrits à ce qu'ils
devraient contenir. Un catalogue oublié fait donc rougir la suite, comme
un `CITATION.cff` désaccordé fait rougir `test_citation.py`.
"""

import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT.parent.parent / "EXstat_project" / "stase" / "src"))

from card.extraction import _DEFAULT_CARD_DIR, _find_cards, _meta_frame  # noqa: E402
from card.loader import load_card  # noqa: E402
from card.render import unite  # noqa: E402


def _inputs(raw):
    """Les colonnes que `data` doit contenir, sans leur unité.

    L'unité de chaque entrée est dans `inputs.yaml` et dans la fiche : la
    répéter ici allongeait des lignes déjà larges, pour une information
    qu'on ne scanne pas. On lit `Q, T`, pas `Q [m^{3}.s^{-1}], T [°C]`.
    """
    out = []
    for var in str(raw).split(","):
        var = var.strip()
        if var:
            out.append(var)
    return ", ".join(out)


# Le catalogue est écrit dans les DEUX langues du corpus, chaque fiche
# les portant toutes deux. N'en publier qu'une jetait la moitié de ce que
# les fiches disent, et laissait un lecteur anglophone devant des noms
# français.
OUT = {"en": ROOT / "docs" / "CARDS.md",
       "fr": ROOT / "docs" / "CARDS.fr.md"}
# Le décompte du corpus (fiches, variables) ne vit qu'à UN endroit : le
# README, entre les balises ci-dessous, resynchronisé ici pour qu'il ne
# puisse jamais dériver. Ne jamais l'écrire à la main ailleurs (ni dans
# CLAUDE.md, ni dans les docs) : ça finit toujours périmé.
README = ROOT / "README.md"
README_COUNT = re.compile(
    r"(<!-- cards:count -->)(.*?)(<!-- /cards:count -->)", re.S)


def count_label(n_cards, n_vars):
    """Le décompte tel qu'il s'écrit entre les balises du README.

    `n_vars` compte les variables DISTINCTES, et pas les lignes des deux
    catalogues markdown, qui listent par fiche : vingt-huit variables
    sont produites par deux fiches (`centerLF` vient de sa fiche et de la
    fiche groupée `allLF`), si bien que le corpus rend 472 colonnes pour
    444 variables. Le README annonçait les colonnes en disant
    « variables ». Les deux nombres sont vrais, mais celui qu'un lecteur
    cherche est le nombre de choses différentes qu'il peut calculer.
    """
    return f"{n_cards} cards, {n_vars} variables"


def _sync_readme(n_cards, n_vars):
    if not README.exists():
        return
    text = README.read_text(encoding="utf-8")
    new = README_COUNT.sub(
        rf"\g<1>{count_label(n_cards, n_vars)}\g<3>", text)
    if new != text:
        README.write_text(new, encoding="utf-8")
        print(f"{README} : décompte resynchronisé ({n_cards}, {n_vars})")


# Ordre des domaines dans le catalogue (le débit en premier, le plus
# fourni) ; les phénomènes sont ensuite alphabétiques dans chaque domaine.
_DOMAIN_ORDER = ["flow", "precipitation", "temperature", "evapotranspiration"]
_FORM_ORDER = {"série": 0, "scalaire": 1, "courbe": 2}


def _anchor(section):
    """Ancre GitHub d'un titre : minuscules, non-alphanumériques retirés,
    espaces en tirets."""
    return re.sub(r"[^\w\s-]", "", section.lower()).replace(" ", "-")


# En-tête : le décodage d'un nom, en quatre lignes. C'est le meilleur
# levier de découvrabilité du catalogue : sans lui, 226 identifiants sont
# opaques ; avec lui, ils se PRÉDISENT. La grammaire complète est dans
# docs/dev/NOMENCLATURE.md, on n'en met ici que de quoi lire un nom.
_ENTETE = {
    "en": [
        "# CARD catalogue",
        "",
        "Generated by `scripts/generate_catalog.py`, do not edit by hand. "
        "The corpus count is in the README. "
        "[Version française](CARDS.fr.md).",
        "",
        "**Reading a name.** Identifiers are systematic, and read left to "
        "right: quantity (`Q` discharge, `R` precipitation, `T` "
        "temperature, `ETP` evapotranspiration), time step (`A` year, `M` "
        "month, `S` season, `J` day), order statistic (`N` minimum, `D` "
        "median, `X` maximum, nothing = mean), season. A prefix transforms "
        "the output (`delta-` change between two periods, `mean-`/`median-` "
        "inter-annual, `rp-` return period), a suffix qualifies it (`-10` "
        "ten-year return period, `_summer`, `_H` projection horizon). So "
        "`QJXA` reads discharge, daily, maximum, annual. Full grammar: "
        "[NOMENCLATURE.md](dev/NOMENCLATURE.md).",
        "",
        "Filed by **domain / phenomenon**. Each card runs through "
        "`card.extract(data, cards=[...])`; *inputs* are the columns `data` "
        "must contain (see `rename=`). Details of one card: "
        "`card.info(\"name\")`.",
        "",
    ],
    "fr": [
        "# Catalogue des fiches CARD",
        "",
        "Généré par `scripts/generate_catalog.py`, ne pas éditer à la main. "
        "Le décompte du corpus est dans le README. "
        "[English version](CARDS.md).",
        "",
        "**Lire un nom.** Les identifiants sont systématiques et se lisent "
        "de gauche à droite : grandeur (`Q` débit, `R` précipitations, `T` "
        "température, `ETP` évapotranspiration), pas de temps (`A` année, "
        "`M` mois, `S` saison, `J` jour), statistique d'ordre (`N` minimum, "
        "`D` médiane, `X` maximum, rien = moyenne), saison. Un préfixe "
        "transforme la sortie (`delta-` changement entre deux périodes, "
        "`mean-`/`median-` inter-annuel, `rp-` période de retour), un "
        "suffixe la qualifie (`-10` période de retour 10 ans, `_summer`, "
        "`_H` horizon de projection). Ainsi `QJXA` se lit débit, "
        "journalier, maximum, annuel. Grammaire complète : "
        "[NOMENCLATURE.md](dev/NOMENCLATURE.md).",
        "",
        "Rangé par **domaine / phénomène**. Chaque fiche s'exécute via "
        "`card.extract(data, cards=[...])` ; *entrées* indique les colonnes "
        "que `data` doit contenir (cf. `rename=`). Détail d'une fiche : "
        "`card.info(\"nom\")`.",
        "",
    ],
}

_COLONNES = {
    "en": "| card | name | variables | facets | unit | inputs | exp. |",
    "fr": "| fiche | nom | variables | facettes | unité | entrées | exp. |",
}
_SOMMAIRE = {"en": "## Contents", "fr": "## Sommaire"}


def render(lang="fr"):
    """Le catalogue d'une langue et son décompte, sans rien écrire.

    Séparé de `main` pour qu'un test puisse comparer le fichier écrit à
    ce qu'il devrait être : une garde qui régénère elle-même n'en serait
    pas une.
    """
    cards = _find_cards(_DEFAULT_CARD_DIR, None)
    sections = defaultdict(list)   # "domaine / phénomène" -> [(nom, meta, rel)]

    for name, path in sorted(cards.items()):
        rel = path.relative_to(_DEFAULT_CARD_DIR)
        # rel.parts = (domaine, phénomène-ou-purpose, forme, fichier)
        section = " / ".join(p.replace("-", " ") for p in rel.parts[:2])
        # _meta_frame (et non _meta_rows) : le catalogue doit montrer la
        # forme par défaut d'une fiche à placeholders, jamais l'accolade.
        meta = _meta_frame(load_card(path))
        sections[section].append((name, meta, rel))

    n_cards = len(cards)
    n_vars = sum(len(m) for grp in sections.values() for _, m, _ in grp)

    def _sect_key(section):
        dom = section.split(" / ")[0]
        return (_DOMAIN_ORDER.index(dom) if dom in _DOMAIN_ORDER else 99, section)

    ordered = sorted(sections, key=_sect_key)

    lines = list(_ENTETE[lang]) + [_SOMMAIRE[lang], ""]
    for section in ordered:
        lines.append(f"- [{section}](#{_anchor(section)}) "
                     f"({len(sections[section])})")
    lines.append("")

    for section in ordered:
        lines += [f"## {section}", "",
                  _COLONNES[lang], "|---|---|---|---|---|---|---|"]

        def _form(row):
            return str(row[1]["output_fr"].iloc[0])

        for name, meta, rel in sorted(
                sections[section],
                key=lambda r: (_FORM_ORDER.get(_form(r), 9), r[0])):
            label = str(meta[f"name_{lang}"].iloc[0]) or str(meta["name_en"].iloc[0])
            # `unite()` est celle de la figure : le catalogue et `card.info`
            # doivent écrire une unité de la même façon, et lisiblement
            # (m³·s⁻¹ plutôt que m^{3}.s^{-1}).
            unit = unite(meta[f"unit_{lang}"].iloc[0])
            inputs = _inputs(meta["input_vars"].iloc[0])
            exp = "⚠" if bool(meta["is_experimental"].iloc[0]) else ""

            def facet(col):
                vals = [str(v) for v in meta[col] if str(v)]
                uniq = sorted(set(vals), key=vals.index)
                return ", ".join(uniq)

            # Les facettes tiennent dans une cellule : on les scanne
            # ensemble, et trois colonnes de plus poussaient la table
            # hors de l'écran.
            facettes = " · ".join(f for f in (facet(f"output_{lang}"),
                                              facet(f"season_{lang}"),
                                              facet(f"aspect_{lang}")) if f)
            # La colonne `variables` ne dit quelque chose que si la fiche
            # sort autre chose que son propre nom : ailleurs elle répétait
            # la première colonne.
            variables = [str(v) for v in meta["variable_en"]]
            sorties = ", ".join(variables) if variables != [name] else ""
            link = (f"[{name}](https://github.com/lou-heraut/card/"
                    f"blob/main/src/card/cards/{rel.as_posix()})")
            lines.append(
                f"| {link} | {label} | {sorties} | {facettes} "
                f"| {unit} | {inputs} | {exp} |"
            )
        lines.append("")

    return "\n".join(lines), n_cards, n_vars, len(sections)






# ── Le site : la page catalogue, et une page par fiche ───────────────────────
#
# Quatre rendus du même corpus, quatre publics, et c'est voulu :
#   docs/CARDS.md, CARDS.fr.md   le dépôt, lisible sur GitHub sans rien bâtir
#   docs/catalogue.md            le site : une entrée par VARIABLE, filtrable
#   docs/cards/<id>.md           le site : une page par FICHE, sa figure
#   docs/card.ttl                les machines (scripts/generate_skos.py)
#
# LA RÈGLE QUI TIENT TOUT ÇA, et qu'il ne faut pas défaire : le site
# n'invente AUCUNE façon de montrer une fiche. Le détail d'une fiche,
# c'est la figure de `card.figure()`, celle que `card.info()` imprime et
# que card-api sert sur `/v1/cards/{id}/figure`, recopiée telle quelle.
# Un rendu de plus serait une chose de plus à tenir d'accord avec les
# autres, et un visiteur qui a vu la fiche dans le terminal, dans l'API
# et sur le site aurait vu trois objets différents.
#
# Le catalogue, lui, ne montre que ce qui est propre à une VARIABLE et
# qu'une figure de fiche ne porte pas : ses entrées, ses variantes, la ou
# les fiches qui la produisent. Il l'écrit clé par clé, comme le YAML
# dont ça sort et comme l'en-tête de la figure.
SITE = ROOT / "docs" / "catalogue.md"
CARTES = ROOT / "docs" / "cards"
DEPOT = "https://github.com/lou-heraut/card/blob/main/src/card/cards/"

# Les facettes proposées en menu, dans l'ordre où on les parcourt : du
# plus large (quelle grandeur) au plus précis (quelle finalité).
_FACETTES_SITE = ("domain", "phenomenon", "aspect", "statistic",
                  "season", "output", "purpose")

# Au-delà, la liste des variantes est un mur de symboles : on en montre
# quelques-unes et on renvoie au filtre, qui les donne toutes.
_VARIANTES_MONTREES = 8


def _esc(x):
    """Échappe pour du HTML. Les libellés viennent des fiches, donc de la
    donnée : ne pas les traiter comme du balisage."""
    return (str(x).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def _bilingue(en, fr, balise="span", classe=""):
    """Un fragment qui porte ses DEUX langues, ou une seule si elles
    coïncident.

    C'est ce que deux fichiers markdown ne savaient pas faire : la
    bascule masque une langue au lieu de recharger une autre page. Un
    symbole identique dans les deux langues (`VCN10`) ne s'écrit qu'une
    fois, un symbole qui diffère (`ETPMA_apr` / `ETPMA_avril`) s'écrit
    deux fois. La page reste donc lisible sans JavaScript : elle affiche
    alors l'anglais, jamais rien de vide.
    """
    en, fr = str(en or ""), str(fr or "")
    cl = f' class="{classe}"' if classe else ""
    if en == fr:
        return f"<{balise}{cl}>{_esc(en)}</{balise}>"
    return (f'<{balise}{cl} lang="en">{_esc(en)}</{balise}>'
            f'<{balise}{cl} lang="fr">{_esc(fr)}</{balise}>')


def _slugs(row, facette, slug_de):
    """Les slugs d'une facette pour une ligne, une facette pouvant en
    porter plusieurs (`domain: flow, precipitation`)."""
    brut = str(row.get(f"{facette}_en", "") or "")
    return [slug_de(facette, x.strip()) or x.strip().lower()
            for x in brut.split(",") if x.strip()]


def _cadre(df):
    """Le corpus tel que le site le range : une entrée par VARIABLE.

    Les deux markdown listent par FICHE, ce qui est la bonne unité quand
    on parcourt une arborescence. Ici l'unité est la variable, parce que
    c'est elle qu'on cherche, et parce que 28 variables sont produites
    par deux fiches : les lister deux fois donnerait deux entrées pour un
    même concept, et deux ancres pour une même URL.
    """
    from card.schema import _slug_of, input_registry, vocabulary

    vocab = vocabulary()
    registre = input_registry()

    # Les familles servent aux « variantes » : les frères sémantiques
    # d'une variable, ceux qui ne diffèrent que par un paramètre.
    familles = {}
    for fam, g in df.groupby("family"):
        familles[fam] = list(dict.fromkeys(g["variable_en"]))

    entrees = []
    for var, g in df.groupby("variable_en", sort=False):
        r = g.iloc[0]
        facettes = {}
        for f in _FACETTES_SITE:
            vus = []
            for _, ligne in g.iterrows():
                for s in _slugs(ligne, f, _slug_of):
                    if s not in vus:
                        vus.append(s)
            facettes[f] = vus
        # Les paramètres de période (`ref_start`, `horizon_end`…) sont
        # des dates fournies par l'appelant, pas des grandeurs observées :
        # ils encombreraient le filtre des entrées sans rien distinguer.
        entrees_var = []
        for _, ligne in g.iterrows():
            for x in str(ligne["input_vars"] or "").split(","):
                x = x.strip()
                if x and x not in entrees_var and \
                        registre.get(x, {}).get("type") != "date":
                    entrees_var.append(x)
        fam = str(r["family"])
        entrees.append({
            "var_en": var, "var_fr": str(r["variable_fr"] or var),
            "name_en": r["name_en"], "name_fr": r["name_fr"],
            "desc_en": r["description_en"], "desc_fr": r["description_fr"],
            "unit": unite(r["unit_en"]),
            "inputs": entrees_var,
            "family": fam,
            "variants": [v for v in familles.get(fam, []) if v != var],
            "cards": list(dict.fromkeys(g["card"])),
            "facettes": facettes,
        })

    # ALPHABÉTIQUE, et rien d'autre. Le rangement par régime puis par
    # phénomène était plus savant, mais il ne se VOYAIT pas : rien sur la
    # page n'annonçait les groupes, si bien que l'ordre paraissait
    # arbitraire et qu'on ne pouvait pas deviner où chercher un symbole.
    # Grouper pour de bon, c'est le travail des filtres, et ils le font
    # mieux qu'un ordre implicite. Le rang déclaré du vocabulaire sert
    # encore aux MENUS, où l'ordre est celui d'une liste courte qu'on lit
    # en entier.
    entrees.sort(key=lambda e: e["var_en"].lower())
    return entrees, vocab


def _detail(e):
    """Ce qu'une entrée dit d'elle-même quand on la déplie.

    Clé par clé, une ligne par clé : c'est la forme du YAML dont ça
    sort, et celle de l'en-tête de la figure. Rien ici ne redit ce que
    la figure de la fiche porte déjà (méthode, fenêtre, grain, swhid) :
    on y renvoie.
    """
    lignes = []
    if str(e["desc_en"] or "") or str(e["desc_fr"] or ""):
        lignes.append('<p class="cat-desc">'
                      + _bilingue(e["desc_en"], e["desc_fr"]) + "</p>")

    champs = []
    if e["inputs"]:
        champs.append(("inputs", " ".join(
            f"<code>{_esc(x)}</code>" for x in e["inputs"])))

    if e["variants"]:
        montres = e["variants"][:_VARIANTES_MONTREES]
        liens = " ".join(f'<a href="#{_esc(v)}"><code>{_esc(v)}</code></a>'
                         for v in montres)
        if len(e["variants"]) > len(montres):
            liens += (f' <a class="cat-more" href="?family={_esc(e["family"])}">'
                      f'all {len(e["variants"]) + 1}</a>')
        champs.append(("variants", liens))

    fiches = " ".join(
        f'<a href="../cards/{_esc(c)}/"><code>{_esc(c)}</code></a>'
        for c in e["cards"])
    champs.append(("card", fiches))

    lignes.append("<dl>" + "".join(
        f"<dt>{k}</dt><dd>{v}</dd>" for k, v in champs) + "</dl>")
    return "".join(lignes)


def render_site():
    """La page catalogue du site, et le nombre de variables qu'elle porte.

    Toutes les entrées sont écrites à la construction, dépliage compris :
    le JavaScript ne fait que masquer celles qui ne passent pas le
    filtre, et le dépliage est celui du navigateur (`<details>`), donc il
    marche sans lui. Sans ça la page serait vide pour un moteur de
    recherche, pour qui coupe JS et pour un lecteur d'écran mal servi,
    alors que le catalogue markdown qu'elle remplace est indexable. On ne
    régresse pas là-dessus.
    """
    from card.management import list_cards
    from card.schema import input_registry

    df = list_cards()
    entrees, vocab = _cadre(df)

    corps = []
    for e in entrees:
        # Une facette vide ne s'écrit pas : `purpose` ne concerne que
        # trente et une variables, et 413 attributs vides pèsent autant
        # qu'ils informent peu.
        attrs = " ".join(
            f'data-{f}="{_esc(" ".join(e["facettes"][f]))}"'
            for f in _FACETTES_SITE if e["facettes"][f])
        # Aucun `data-search` : le texte à chercher est DÉJÀ dans
        # l'entrée, symboles, noms et description compris, dans les deux
        # langues. Le recopier dans un attribut pesait 135 ko et créait
        # une seconde version du même texte, qui aurait fini par diverger.
        corps.append(
            f'<details class="cat-row" id="{_esc(e["var_en"])}" {attrs} '
            f'data-inputs="{_esc(" ".join(e["inputs"]))}" '
            f'data-family="{_esc(e["family"])}">'
            f"<summary>"
            + _bilingue(e["var_en"], e["var_fr"], "code", "v")
            + _bilingue(e["name_en"], e["name_fr"], "span", "n")
            + f'<span class="u">{_esc(e["unit"])}</span>'
            + "</summary>"
            + f'<div class="cat-detail">{_detail(e)}</div>'
            + "</details>")

    # Seules les valeurs RÉELLEMENT présentes sont proposées : un menu qui
    # offre un filtre ne rendant rien est une promesse en l'air.
    menus = []
    for f in _FACETTES_SITE:
        presents = {s for e in entrees for s in e["facettes"][f]}
        options = "".join(
            f'<option value="{_esc(slug)}">{_esc(v["en"])} · {_esc(v["fr"])}</option>'
            for slug, v in vocab.get(f, {}).items() if slug in presents)
        if options:
            menus.append(
                f'<label>{f}<select data-facet="{f}">'
                f'<option value="">—</option>{options}</select></label>')

    # Le filtre des entrées répond à la première question d'un arrivant :
    # « qu'est-ce que je peux calculer avec ce que j'ai ? ». Il n'est pas
    # une facette de classification, d'où son menu à part, dans l'ordre
    # du registre.
    presents = {x for e in entrees for x in e["inputs"]}
    options = "".join(
        f'<option value="{_esc(k)}">{_esc(k)} · {_esc(v.get("en", k))}</option>'
        for k, v in input_registry().items() if k in presents)
    menus.append(f'<label>inputs<select data-facet="inputs">'
                 f'<option value="">—</option>{options}</select></label>')

    n = len(entrees)
    return "\n".join([
        "# Catalogue", "",
        "Every variable the collection produces, one per entry. Filter by "
        "facet or search in either language: each entry carries both. "
        "Unfold one for its inputs, its variants and the card that "
        "computes it.", "",
        '<div class="cat-controls">',
        '<input type="search" id="cat-q" placeholder="Search a variable, '
        'a name, an input column…" aria-label="Search the catalogue">',
        "\n".join(menus),
        '<label>labels<select id="cat-lang">'
        '<option value="en">English</option>'
        '<option value="fr">Français</option></select></label>',
        '<button type="button" id="cat-reset">Reset</button>',
        "</div>", "",
        f'<p class="cat-count"><span id="cat-shown">{n}</span> of {n} '
        f"variables, from {df['card'].nunique()} cards</p>", "",
        '<div class="cat-head"><span class="v">variable</span>'
        '<span class="n">name</span><span class="u">unit</span></div>',
        '<div class="cat-list" id="cat-list">',
        "\n".join(corps),
        "</div>", "",
    ]), n


def render_cards():
    """Une page par fiche : {chemin: contenu}.

    La page ne dit presque rien elle-même. Elle porte la FIGURE, dans les
    deux langues, telle que `card.figure()` la rend : c'est le seul rendu
    humain d'une fiche dans tout l'écosystème, et le site en est un
    lecteur de plus, pas un auteur de plus.

    Elle existe parce qu'une ancre dans une longue page n'est pas une
    adresse : une fiche citée dans un article a besoin d'une URL à elle,
    et la recherche du site n'indexe que des pages.
    """
    from card.management import list_cards
    from card.render import figure

    df = list_cards()
    pages = {}
    for nom, g in df.groupby("card"):
        chemin = str(g.iloc[0]["script_path"])
        figures = "\n".join(
            f'<pre class="fig" lang="{lang}" data-search-exclude>'
            f"{_esc(figure(nom, lang=lang))}</pre>"
            for lang in ("en", "fr"))
        # Ce que la fiche produit, EN TOUTES LETTRES et dans les deux
        # langues. C'est ce qui rend une variable trouvable par la
        # recherche du site : la figure est exclue de l'index (un dessin
        # en caractères n'est fait que de bruit pour un moteur), et sans
        # cette liste une page de fiche ne contenait que son symbole.
        # Chercher « centre des basses eaux » ne rendait donc rien, alors
        # que c'est le nom de la variable.
        #
        # La langue cachée reste dans la page, donc dans l'index : on
        # cherche dans une langue et on lit dans l'autre.
        lignes_var = "".join(
            f'<dt><a href="../../catalogue/#{_esc(r["variable_en"])}">'
            f'<code>{_esc(r["variable_en"])}</code></a></dt>'
            f'<dd>{_bilingue(r["name_en"], r["name_fr"])}'
            f'<span class="u">{_esc(unite(r["unit_en"]))}</span></dd>'
            for _, r in g.drop_duplicates("variable_en").iterrows())
        liste = f'<dl class="card-vars">{lignes_var}</dl>'
        pages[CARTES / f"{nom}.md"] = "\n".join([
            # Le sommaire de droite n'aurait qu'une entrée, le titre, et
            # il prend la largeur dont la figure a besoin : elle est
            # dessinée en caractères, donc elle ne se replie pas.
            "---", "hide:", "  - toc", "---", "",
            # Le titre est un SYMBOLE : il s'écrit en chasse fixe, comme
            # partout ailleurs, et les accents graves suffisent à le dire
            # sans rien qui soit propre à MkDocs.
            f"# `{nom}`", "",
            "The card as `card.info()` prints it, as `card4r` prints it, "
            "and as card-api serves it. One drawing, read in three places.",
            "",
            '<div class="cat-controls cat-controls--lang">',
            '<label>labels<select id="cat-lang">'
            '<option value="en">English</option>'
            '<option value="fr">Français</option></select></label>',
            "</div>", "",
            figures, "",
            "**Variables produced**", "",
            liste, "",
            f"[The card itself, on GitHub]({DEPOT}{chemin}) &middot; "
            "[back to the catalogue](../catalogue.md)", "",
        ])
    return pages


def main():
    for lang, chemin in OUT.items():
        texte, n_cards, n_colonnes, n_sections = render(lang)
        chemin.parent.mkdir(parents=True, exist_ok=True)
        chemin.write_text(texte, encoding="utf-8")
        print(f"{chemin} : {n_cards} fiches, {n_colonnes} lignes, "
              f"{n_sections} sections")
    page, n_vars = render_site()
    SITE.write_text(page, encoding="utf-8")
    print(f"{SITE} : {n_vars} variables, une par entrée, filtrable")

    # Le dossier est ENTIÈREMENT engendré : on écrit les pages attendues
    # et on retire celles qui restent. Sans ce ménage, une fiche renommée
    # laisse sa page derrière elle, et le site sert indéfiniment une
    # définition qui n'existe plus, ce qui est arrivé à card4r avec une
    # action de déploiement en `clean: false`.
    pages = render_cards()
    CARTES.mkdir(parents=True, exist_ok=True)
    for chemin, texte in pages.items():
        chemin.write_text(texte, encoding="utf-8")
    for reste in CARTES.glob("*.md"):
        if reste not in pages:
            reste.unlink()
            print(f"{reste} : retirée, plus aucune fiche de ce nom")
    print(f"{CARTES} : {len(pages)} pages de fiche, une figure par page")

    _sync_readme(n_cards, n_vars)


if __name__ == "__main__":
    main()
