# Copyright 2021-2026 Louis Héraut <louis.heraut@inrae.fr>*1
#
# *1 INRAE, UR RiverLy, Villeurbanne, France
#
# This file is part of the card Python package.
#
# card is free software: you can redistribute it and/or modify it under
# the terms of the license in the LICENSE file of this repository.

"""Génère docs/CARDS.md, catalogue des fiches CARD, consultable sur GitHub.

Usage (depuis la racine du repo) :
    .python_env/bin/python scripts/generate_catalog.py

À relancer après tout ajout/modification de fiche YAML. Nul besoin d'y
penser : `render()` ne touche à rien, si bien que
`tests/test_catalogue.py` peut confronter les fichiers écrits à ce qu'ils
devraient contenir. Un catalogue oublié fait donc rougir la suite, comme
un `CITATION.cff` désaccordé fait rougir `test_citation.py`.
"""

import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT.parent.parent / "EXstat_project" / "stase" / "src"))

from card.extraction import _DEFAULT_CARD_DIR, _find_cards, _meta_frame  # noqa: E402
from card.loader import load_card  # noqa: E402
from card.render import unite  # noqa: E402


def _inputs(raw):
    """Les colonnes que `data` doit contenir, sans leur unité.

    L'unité de chaque entrée est dans `inputs.yaml` et dans la fiche : la
    répéter ici allongeait des lignes déjà larges, pour une information
    qu'on ne scanne pas. On lit `Q, T`, pas `Q [m^{3}.s^{-1}], T [°C]`.
    """
    out = []
    for var in str(raw).split(","):
        var = var.strip()
        if var:
            out.append(var)
    return ", ".join(out)


# Le catalogue est écrit dans les DEUX langues du corpus, chaque fiche
# les portant toutes deux. N'en publier qu'une jetait la moitié de ce que
# les fiches disent, et laissait un lecteur anglophone devant des noms
# français.
OUT = {"en": ROOT / "docs" / "CARDS.md",
       "fr": ROOT / "docs" / "CARDS.fr.md"}
# Le décompte du corpus (fiches, variables) ne vit qu'à UN endroit : le
# README, entre les balises ci-dessous, resynchronisé ici pour qu'il ne
# puisse jamais dériver. Ne jamais l'écrire à la main ailleurs (ni dans
# CLAUDE.md, ni dans les docs) : ça finit toujours périmé.
README = ROOT / "README.md"
README_COUNT = re.compile(
    r"(<!-- cards:count -->)(.*?)(<!-- /cards:count -->)", re.S)


def count_label(n_cards, n_vars):
    """Le décompte tel qu'il s'écrit entre les balises du README."""
    return f"{n_cards} cards, {n_vars} variables"


def _sync_readme(n_cards, n_vars):
    if not README.exists():
        return
    text = README.read_text(encoding="utf-8")
    new = README_COUNT.sub(
        rf"\g<1>{count_label(n_cards, n_vars)}\g<3>", text)
    if new != text:
        README.write_text(new, encoding="utf-8")
        print(f"{README} : décompte resynchronisé ({n_cards}, {n_vars})")


# Ordre des domaines dans le catalogue (le débit en premier, le plus
# fourni) ; les phénomènes sont ensuite alphabétiques dans chaque domaine.
_DOMAIN_ORDER = ["flow", "precipitation", "temperature", "evapotranspiration"]
_FORM_ORDER = {"série": 0, "scalaire": 1, "courbe": 2}


def _anchor(section):
    """Ancre GitHub d'un titre : minuscules, non-alphanumériques retirés,
    espaces en tirets."""
    return re.sub(r"[^\w\s-]", "", section.lower()).replace(" ", "-")


# En-tête : le décodage d'un nom, en quatre lignes. C'est le meilleur
# levier de découvrabilité du catalogue : sans lui, 226 identifiants sont
# opaques ; avec lui, ils se PRÉDISENT. La grammaire complète est dans
# docs/dev/NOMENCLATURE.md, on n'en met ici que de quoi lire un nom.
_ENTETE = {
    "en": [
        "# CARD catalogue",
        "",
        "Generated by `scripts/generate_catalog.py`, do not edit by hand. "
        "The corpus count is in the README. "
        "[Version française](CARDS.fr.md).",
        "",
        "**Reading a name.** Identifiers are systematic, and read left to "
        "right: quantity (`Q` discharge, `R` precipitation, `T` "
        "temperature, `ETP` evapotranspiration), time step (`A` year, `M` "
        "month, `S` season, `J` day), order statistic (`N` minimum, `D` "
        "median, `X` maximum, nothing = mean), season. A prefix transforms "
        "the output (`delta-` change between two periods, `mean-`/`median-` "
        "inter-annual, `rp-` return period), a suffix qualifies it (`-10` "
        "ten-year return period, `_summer`, `_H` projection horizon). So "
        "`QJXA` reads discharge, daily, maximum, annual. Full grammar: "
        "[NOMENCLATURE.md](dev/NOMENCLATURE.md).",
        "",
        "Filed by **domain / phenomenon**. Each card runs through "
        "`card.extract(data, cards=[...])`; *inputs* are the columns `data` "
        "must contain (see `rename=`). Details of one card: "
        "`card.info(\"name\")`.",
        "",
    ],
    "fr": [
        "# Catalogue des fiches CARD",
        "",
        "Généré par `scripts/generate_catalog.py`, ne pas éditer à la main. "
        "Le décompte du corpus est dans le README. "
        "[English version](CARDS.md).",
        "",
        "**Lire un nom.** Les identifiants sont systématiques et se lisent "
        "de gauche à droite : grandeur (`Q` débit, `R` précipitations, `T` "
        "température, `ETP` évapotranspiration), pas de temps (`A` année, "
        "`M` mois, `S` saison, `J` jour), statistique d'ordre (`N` minimum, "
        "`D` médiane, `X` maximum, rien = moyenne), saison. Un préfixe "
        "transforme la sortie (`delta-` changement entre deux périodes, "
        "`mean-`/`median-` inter-annuel, `rp-` période de retour), un "
        "suffixe la qualifie (`-10` période de retour 10 ans, `_summer`, "
        "`_H` horizon de projection). Ainsi `QJXA` se lit débit, "
        "journalier, maximum, annuel. Grammaire complète : "
        "[NOMENCLATURE.md](dev/NOMENCLATURE.md).",
        "",
        "Rangé par **domaine / phénomène**. Chaque fiche s'exécute via "
        "`card.extract(data, cards=[...])` ; *entrées* indique les colonnes "
        "que `data` doit contenir (cf. `rename=`). Détail d'une fiche : "
        "`card.info(\"nom\")`.",
        "",
    ],
}

_COLONNES = {
    "en": "| card | name | variables | facets | unit | inputs | exp. |",
    "fr": "| fiche | nom | variables | facettes | unité | entrées | exp. |",
}
_SOMMAIRE = {"en": "## Contents", "fr": "## Sommaire"}


def render(lang="fr"):
    """Le catalogue d'une langue et son décompte, sans rien écrire.

    Séparé de `main` pour qu'un test puisse comparer le fichier écrit à
    ce qu'il devrait être : une garde qui régénère elle-même n'en serait
    pas une.
    """
    cards = _find_cards(_DEFAULT_CARD_DIR, None)
    sections = defaultdict(list)   # "domaine / phénomène" -> [(nom, meta, rel)]

    for name, path in sorted(cards.items()):
        rel = path.relative_to(_DEFAULT_CARD_DIR)
        # rel.parts = (domaine, phénomène-ou-purpose, forme, fichier)
        section = " / ".join(p.replace("-", " ") for p in rel.parts[:2])
        # _meta_frame (et non _meta_rows) : le catalogue doit montrer la
        # forme par défaut d'une fiche à placeholders, jamais l'accolade.
        meta = _meta_frame(load_card(path))
        sections[section].append((name, meta, rel))

    n_cards = len(cards)
    n_vars = sum(len(m) for grp in sections.values() for _, m, _ in grp)

    def _sect_key(section):
        dom = section.split(" / ")[0]
        return (_DOMAIN_ORDER.index(dom) if dom in _DOMAIN_ORDER else 99, section)

    ordered = sorted(sections, key=_sect_key)

    lines = list(_ENTETE[lang]) + [_SOMMAIRE[lang], ""]
    for section in ordered:
        lines.append(f"- [{section}](#{_anchor(section)}) "
                     f"({len(sections[section])})")
    lines.append("")

    for section in ordered:
        lines += [f"## {section}", "",
                  _COLONNES[lang], "|---|---|---|---|---|---|---|"]

        def _form(row):
            return str(row[1]["output_fr"].iloc[0])

        for name, meta, rel in sorted(
                sections[section],
                key=lambda r: (_FORM_ORDER.get(_form(r), 9), r[0])):
            label = str(meta[f"name_{lang}"].iloc[0]) or str(meta["name_en"].iloc[0])
            # `unite()` est celle de la figure : le catalogue et `card.info`
            # doivent écrire une unité de la même façon, et lisiblement
            # (m³·s⁻¹ plutôt que m^{3}.s^{-1}).
            unit = unite(meta[f"unit_{lang}"].iloc[0])
            inputs = _inputs(meta["input_vars"].iloc[0])
            exp = "⚠" if bool(meta["is_experimental"].iloc[0]) else ""

            def facet(col):
                vals = [str(v) for v in meta[col] if str(v)]
                uniq = sorted(set(vals), key=vals.index)
                return ", ".join(uniq)

            # Les facettes tiennent dans une cellule : on les scanne
            # ensemble, et trois colonnes de plus poussaient la table
            # hors de l'écran.
            facettes = " · ".join(f for f in (facet(f"output_{lang}"),
                                              facet(f"season_{lang}"),
                                              facet(f"aspect_{lang}")) if f)
            # La colonne `variables` ne dit quelque chose que si la fiche
            # sort autre chose que son propre nom : ailleurs elle répétait
            # la première colonne.
            variables = [str(v) for v in meta["variable_en"]]
            sorties = ", ".join(variables) if variables != [name] else ""
            link = (f"[{name}](https://github.com/lou-heraut/card/"
                    f"blob/main/src/card/cards/{rel.as_posix()})")
            lines.append(
                f"| {link} | {label} | {sorties} | {facettes} "
                f"| {unit} | {inputs} | {exp} |"
            )
        lines.append("")

    return "\n".join(lines), n_cards, n_vars, len(sections)






# ── La page catalogue du site ────────────────────────────────────────────────
#
# Trois rendus du même corpus, trois publics, et c'est voulu :
#   docs/CARDS.md, CARDS.fr.md   le dépôt, lisible sur GitHub sans rien bâtir
#   docs/catalogue.md            le site, une ligne par VARIABLE, filtrable
#   docs/card.ttl                les machines (scripts/generate_skos.py)
#
# Le site part de `list_cards()` et non de l'arborescence : une ligne par
# variable produite, avec ses deux libellés et ses facettes. C'est ce qui
# rend le filtrage possible, et surtout ce qui garantit que la page ne
# peut pas diverger du paquet, puisqu'elle affiche exactement ce que la
# fonction publique rend.
SITE = ROOT / "docs" / "catalogue.md"

# Les facettes proposées en menu, dans l'ordre où on les parcourt : du
# plus large (quelle grandeur) au plus précis (quelle forme de sortie).
_FACETTES_SITE = ("domain", "phenomenon", "aspect", "statistic",
                  "season", "output")


def _esc(x):
    """Échappe pour du HTML. Les libellés viennent des fiches, donc de la
    donnée : ne pas les traiter comme du balisage."""
    return (str(x).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def render_site():
    """La page catalogue du site, en HTML complet, et son décompte.

    Le tableau ENTIER est écrit à la construction : le JavaScript ne fait
    que masquer des lignes déjà présentes. Sans ça la page serait vide
    pour un moteur de recherche, pour qui coupe JS et pour un lecteur
    d'écran mal servi, alors que le catalogue markdown d'aujourd'hui est
    indexable. On ne régresse pas là-dessus.
    """
    from card.management import list_cards
    from card.schema import vocabulary, _slug_of

    df = list_cards().sort_values(["domain_en", "phenomenon_en", "variable_en"])
    vocab = vocabulary()

    lignes = []
    for _, r in df.iterrows():
        # Les facettes voyagent en SLUG dans les attributs (l'identifiant
        # du concept, stable quand un libellé est reformulé) et en libellé
        # dans les menus. Une facette multi-valeurs garde ses deux slugs.
        attrs = []
        for f in _FACETTES_SITE:
            brut = str(r.get(f"{f}_en", "") or "")
            slugs = [_slug_of(f, x.strip()) or x.strip().lower()
                     for x in brut.split(",") if x.strip()]
            attrs.append(f'data-{f}="{_esc(" ".join(slugs))}"')
        # Une seule chaîne de recherche, minuscule, couvrant les deux
        # langues : le visiteur cherche « étiage » ou « low flow » sans
        # avoir à savoir dans quelle langue la page est réglée.
        cherche = " ".join(str(r.get(c, "") or "") for c in (
            "variable_en", "variable_fr", "name_en", "name_fr",
            "description_en", "description_fr", "card", "input_vars")).lower()
        attrs.append(f'data-search="{_esc(cherche)}"')

        chemin = str(r["script_path"])
        lien = (f'<a href="https://github.com/lou-heraut/card/blob/main/'
                f'src/card/cards/{_esc(chemin)}">{_esc(r["card"])}</a>')
        lignes.append(
            f'<tr {" ".join(attrs)}>'
            f'<td class="v"><code>{_esc(r["variable_en"])}</code></td>'
            f'<td lang="en">{_esc(r["name_en"])}</td>'
            f'<td lang="fr">{_esc(r["name_fr"])}</td>'
            f'<td class="u">{_esc(unite(r["unit_en"]))}</td>'
            f'<td class="i"><code>{_esc(_inputs(r["input_vars"]))}</code></td>'
            f'<td class="c">{lien}</td>'
            f"</tr>"
        )

    menus = []
    for f in _FACETTES_SITE:
        # Seules les valeurs RÉELLEMENT présentes sont proposées : un menu
        # qui offre un filtre ne rendant rien est une promesse en l'air.
        presents = set()
        for v in df[f"{f}_en"]:
            for x in str(v or "").split(","):
                if x.strip():
                    presents.add(_slug_of(f, x.strip()) or x.strip().lower())
        options = "".join(
            f'<option value="{_esc(slug)}">{_esc(e["en"])} · {_esc(e["fr"])}</option>'
            for slug, e in vocab.get(f, {}).items() if slug in presents)
        if options:
            menus.append(
                f'<label>{f}<select data-facet="{f}">'
                f'<option value="">—</option>{options}</select></label>')

    return "\n".join([
        "# Catalogue", "",
        "Every variable the collection produces, one per row. Filter by "
        "facet or search in either language: the table carries both.", "",
        '<div class="cat-controls">',
        '<input type="search" id="cat-q" placeholder="Search a variable, '
        'a name, an input column…" aria-label="Search the catalogue">',
        "\n".join(menus),
        '<label>labels<select id="cat-lang">'
        '<option value="en">English</option>'
        '<option value="fr">français</option></select></label>',
        '<button type="button" id="cat-reset">Reset</button>',
        "</div>", "",
        '<p class="cat-count"><span id="cat-shown">'
        f"{len(df)}</span> of {len(df)} variables</p>", "",
        '<table class="cat" id="cat-table">',
        "<thead><tr><th>variable</th>"
        '<th lang="en">name</th><th lang="fr">nom</th>'
        "<th>unit</th><th>inputs</th><th>card</th></tr></thead>",
        "<tbody>",
        "\n".join(lignes),
        "</tbody></table>", "",
    ]), len(df)


def main():
    for lang, chemin in OUT.items():
        texte, n_cards, n_vars, n_sections = render(lang)
        chemin.parent.mkdir(parents=True, exist_ok=True)
        chemin.write_text(texte, encoding="utf-8")
        print(f"{chemin} : {count_label(n_cards, n_vars)}, "
              f"{n_sections} sections")
    page, n_lignes = render_site()
    SITE.write_text(page, encoding="utf-8")
    print(f"{SITE} : {n_lignes} variables, une par ligne, filtrable")
    _sync_readme(n_cards, n_vars)


if __name__ == "__main__":
    main()
